# Generated by Django 5.1.15 on 2026-09-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('bordereau', 'Bordereau de livraison'), ('provisoire', 'Bordereau provisoire'), ('proforma', 'Facture proforma')], max_length=20)),
                ('number', models.CharField(max_length=50)),
                ('issued_at', models.DateField()),
                ('issued_place', models.CharField(blank=True, max_length=120)),
                ('client', models.CharField(max_length=255)),
                ('object_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('final', 'Finalisé')], default='draft', max_length=10)),
                ('generated_pdf', models.FileField(blank=True, upload_to='documents/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('designation', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observation', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.document')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
