# Generated by Django 5.1.15 on 2026-09-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_signatory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentline',
            name='is_taxable',
            field=models.BooleanField(default=False),
        ),
    ]
