# Generated by Django 5.1.15 on 2026-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_letterhead_header_color'),
        ('documents', '0003_documentline_is_taxable'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('company', 'doc_type', 'number'), name='unique_number_per_company_doc_type'),
        ),
    ]
