# Generated by Django 5.1.15 on 2026-09-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterhead',
            name='header_color',
            field=models.CharField(default='#eeeeee', help_text='Couleur dominante détectée, en hexadécimal', max_length=7),
        ),
    ]
