# Generated by Django 5.1.15 on 2026-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_letterhead_header_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stamp_image',
            field=models.ImageField(blank=True, null=True, upload_to='stamps/'),
        ),
    ]
